### ISSUE TITLE
可视化界面上面的选项 , 请问支持aab吗

### ISSUE THREAD

**Issue by huangzhewei** [TimScriptov/nmmp#1]

**Comment by timscriptov** [comment]
There is no pure theory, the resource parser cannot read the manifest in bundles

**Comment by huangzhewei** [comment]
您能写一个支持aab加固的便捷式可视化界面吗 , 谢谢

**Comment by timscriptov** [comment]
There are plans for the future, but I don’t know when the time will come. At the moment you can use converters (apk2aab and vice versa)

**Comment by huangzhewei** [comment]
别未来 , 现在就开始做吧  我为你加油~

**Comment by huangzhewei** [comment]
有在做了吗 , 等你消息

**Comment by timscriptov** [comment]
I'm currently developing a server for a personal project.  I have implemented everything I wanted in this repository at the moment.  I won't be back soon to write new code.

**Comment by timscriptov** [comment]
Also, this project does not satisfy my needs, it does not work stably.  Various errors occur after encryption

**Comment by huangzhewei** [comment]
你已经实现了，可以发给我使用一下吗，谢谢



---原始邮件---
发件人: "Иван ***@***.***&gt;
发送时间: 2023年9月16日(周六) 晚上10:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TimScriptov/nmmp] 可视化界面上面的选项 , 请问支持aab吗 (Issue #1)




 
I'm currently developing a server for a personal project.  I have implemented everything I wanted in this repository at the moment.  I won't be back soon to write new code.

**Comment by huangzhewei** [comment]
是有更好的方案吗，分享一下，谢谢



---原始邮件---
发件人: "Иван ***@***.***&gt;
发送时间: 2023年9月16日(周六) 晚上10:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TimScriptov/nmmp] 可视化界面上面的选项 , 请问支持aab吗 (Issue #1)




 
Also, this project does not satisfy my needs, it does not work stably.  Various errors occur after encryption

**Comment by timscriptov** [comment]
I tried VMP, dex2s and they all have disadvantages. Difficult to find good products in the public domain

**Comment by timscriptov** [comment]
Done

https://github.com/TimScriptov/nmmp/commit/ac8ef092fc4215f6cc306865288fa65f8b7882d7
